// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireSet

import (
	"github.com/google/wire"
	"go-study/go-wire/model"
)

// Injectors from wire.go:

func InitializeBroadCast() model.BroadCast {
	message := model.NewMessage()
	channel := model.NewChannel(message)
	broadCast := model.NewBroadcast(channel)
	return broadCast
}

// wire.go:

var providerSet = wire.NewSet(model.NewBroadcast, model.NewChannel, model.NewMessage)
