// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireClean

import (
	"go-study/go-wire/model"
)

// Injectors from wire.go:

func InitializeBroadCast() (model.BroadCast, func(), error) {
	message, cleanup, err := model.NewMessageWithClose()
	if err != nil {
		return model.BroadCast{}, nil, err
	}
	channel := model.NewChannel(message)
	broadCast := model.NewBroadcast(channel)
	return broadCast, func() {
		cleanup()
	}, nil
}
